name = "Hugo Supper Fresh"
license = "MIT"
licenselink = "https://github.com/StefMa/hugo-fresh/blob/master/LICENSE.md"
description = "A Hugo adaptation of the Fresh theme from CSS Ninja"
homepage = "https://github.com/anggiadiputra/hugo-supperfresh"
tags = ["responsive", "one page", "light", "onepage", "company", "clean", "landing page"]
features = []
min_version = "0.45"

[author]
  name = "Anggi Adi Putra"
  homepage = "https://github.com/Anggi Adi Putra"
